Adding logic to skip building if archives already exist
## Description 
1. Adding logic to skip building if archives already exist.
2. Testing file existence before copying to avoid errors
3. Clean up variables

## Test Plan 

https://github.com/GeunhwaJeong/haneul/actions/runs/7199617823/job/19611841832

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,6 +35,7 @@ env:
 
 jobs:
   release-build:
+    name: Build & Publish Binaries
     timeout-minutes: 80
     strategy:
       matrix:
@@ -42,6 +43,13 @@ jobs:
       fail-fast: false
     runs-on: ${{ matrix.os }}
     steps:
+      - name: Clean up and validate tag name ${{ env.TAG_NAME }}
+        shell: bash
+        run: |
+          export haneul_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)
+          [[ "${haneul_tag}" == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
+          echo "haneul_tag=${haneul_tag}" >> $GITHUB_ENV
+
       - name: Configure AWS credentials
         if: ${{ env.TAG_NAME != 'main' }}
         uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # pin@v1
@@ -50,34 +58,53 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
 
-      - name: Clean up tag name ${{ env.TAG_NAME }}
+      - name: Set os/arch variables (Windows)
+        if: ${{ matrix.os == 'windows-ghcloud' }}
         shell: bash
-        run: | 
-          echo "haneul_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
+        run: |
+          export arch=$(uname -m)
+          export os_type="windows-${arch}"
+          echo "os_type=${os_type}" >> $GITHUB_ENV
 
-      - name: Checking out ${{ env.haneul_tag }}
-        if: ${{ env.haneul_tag != 'main' }}
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ env.haneul_tag }}
+      - name: Set os/arch variables
+        if: ${{ matrix.os != 'windows-ghcloud' }}
+        shell: bash
+        run: |
+          export arch=$(uname -m)
+          export system_os=$(echo ${{ matrix.os }} | cut -d- -f1)
+          export os_type="${system_os}-${arch}"
+          echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV     
+
+      - name: Check if archives of binaries have already been built
+        continue-on-error: true
+        shell: bash
+        run: |
+          echo "s3_archive_exist=$(curl -Is https://haneul-releases.s3.us-east-1.amazonaws.com/releases/haneul-${{ env.haneul_tag }}-${{ env.os_type }}.tgz | head -n 1 | grep '200 OK')" >> $GITHUB_ENV
+
+      - name: Download archive, if it exists
+        if: ${{ env.s3_archive_exist != '' }}
+        shell: bash
+        run: |
+          mkdir -p ./target/release
+          aws s3 cp s3://haneul-releases/releases/haneul-${{ env.haneul_tag }}-${os_type}.tgz ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz
 
       - name: Setup caching
-        if: ${{ env.haneul_tag != 'main' }}
+        if: ${{ env.s3_archive_exist == '' }}
         uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths          
       
       - name: Install nexttest (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.haneul_tag != 'main'  }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         uses: taiki-e/install-action@nextest
 
       - name: Setup protoc (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.haneul_tag != 'main'  }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         uses: arduino/setup-protoc@v1
         # this avoids rate-limiting
         with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Install postgres (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.haneul_tag != 'main'  }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         shell: bash
         run: |
           choco install postgresql12 --force --params '/Password:root'
@@ -85,54 +112,51 @@ jobs:
           echo "C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_PATH
           echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_ENV
           echo "PG_DATABASE_URL=postgres://postgres:root@localhost/" >> $GITHUB_ENV
-          echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV          
+          echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV
+
+      - name: Checking out ${{ env.haneul_tag }}
+        if: ${{ env.s3_archive_exist == '' }}
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ env.haneul_tag }}        
 
       - name: cargo build (release) for ${{ matrix.os }} platform
-        if: ${{ env.haneul_tag != 'main' }}
+        if: ${{ env.s3_archive_exist == '' }}
         shell: bash
         run: |
           [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release
           cd external-crates/move && cargo build -p move-analyzer --release
 
       - name: Rename binaries for ${{ matrix.os }}
-        if: ${{ env.haneul_tag != 'main' && matrix.os != 'windows-ghcloud' }}
+        if: ${{ matrix.os != 'windows-ghcloud' && env.s3_archive_exist == '' }}
         shell: bash
         run: |
-          export arch=$(uname -m)
-          export system_os=$(echo ${{ matrix.os }} | cut -d- -f1)
-          export os_type="${system_os}-${arch}"
-          echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV
-          mv ./target/release/haneul ./target/release/haneul-${os_type}
-          mv ./target/release/haneul-node ./target/release/haneul-node-${os_type}
-          mv ./target/release/haneul-tool ./target/release/haneul-tool-${os_type}
-          mv ./target/release/haneul-faucet ./target/release/haneul-faucet-${os_type}
-          mv ./target/release/haneul-test-validator ./target/release/haneul-test-validator-${os_type}
-          mv ./target/release/haneul-indexer ./target/release/haneul-indexer-${os_type}
-          mv ./target/release/haneul-data-ingestion ./target/release/haneul-data-ingestion-${os_type}
-          mv ./external-crates/move/target/release/move-analyzer ./external-crates/move/target/release/move-analyzer-${os_type}
+          [ -f ./target/release/haneul ] && mv ./target/release/haneul ./target/release/haneul-${os_type}
+          [ -f ./target/release/haneul-node ] && mv ./target/release/haneul-node ./target/release/haneul-node-${os_type}
+          [ -f ./target/release/haneul-tool ] && mv ./target/release/haneul-tool ./target/release/haneul-tool-${os_type}
+          [ -f ./target/release/haneul-faucet ] && mv ./target/release/haneul-faucet ./target/release/haneul-faucet-${os_type}
+          [ -f ./target/release/haneul-test-validator ] && mv ./target/release/haneul-test-validator ./target/release/haneul-test-validator-${os_type}
+          [ -f ./target/release/haneul-data-ingestion ] && mv ./target/release/haneul-data-ingestion ./target/release/haneul-data-ingestion-${os_type}
+          [ -f ./external-crates/move/target/release/move-analyzer ] && mv ./external-crates/move/target/release/move-analyzer ./external-crates/move/target/release/move-analyzer-${os_type}
           tar -cvzf ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz ./target/release/haneul*-${os_type}* ./external-crates/move/target/release/move-analyzer-${os_type}
           [[ ${{ env.haneul_tag }} == *"mainnet"* ]] && aws s3 cp ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz s3://haneul-releases/releases/haneul-${{ env.haneul_tag }}-${os_type}.tgz || true
 
       - name: Rename binaries for Windows
-        if: ${{ env.haneul_tag != 'main' && matrix.os == 'windows-ghcloud' }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         shell: bash
         run: |
-          export arch=$(uname -m)
-          export os_type="windows-${arch}"
-          echo "os_type=${os_type}" >> $GITHUB_ENV
-          mv ./target/release/haneul.exe ./target/release/haneul-${os_type}.exe
-          mv ./target/release/haneul-node.exe ./target/release/haneul-node-${os_type}.exe
-          mv ./target/release/haneul-tool.exe ./target/release/haneul-tool-${os_type}.exe
-          mv ./target/release/haneul-faucet.exe ./target/release/haneul-faucet-${os_type}.exe
-          mv ./target/release/haneul-test-validator.exe ./target/release/haneul-test-validator-${os_type}.exe
-          mv ./target/release/haneul-indexer.exe ./target/release/haneul-indexer-${os_type}.exe
-          mv ./target/release/haneul-data-ingestion.exe ./target/release/haneul-data-ingestion-${os_type}.exe
-          mv ./external-crates/move/target/release/move-analyzer.exe ./external-crates/move/target/release/move-analyzer-${os_type}.exe
+          [ -f ./target/release/haneul.exe ] && mv ./target/release/haneul.exe ./target/release/haneul-${os_type}.exe
+          [ -f ./target/release/haneul-node.exe ] && mv ./target/release/haneul-node.exe ./target/release/haneul-node-${os_type}.exe
+          [ -f ./target/release/haneul-tool.exe ] && mv ./target/release/haneul-tool.exe ./target/release/haneul-tool-${os_type}.exe
+          [ -f ./target/release/haneul-faucet.exe ] && mv ./target/release/haneul-faucet.exe ./target/release/haneul-faucet-${os_type}.exe
+          [ -f ./target/release/haneul-test-validator.exe ] && mv ./target/release/haneul-test-validator.exe ./target/release/haneul-test-validator-${os_type}.exe
+          [ -f ./target/release/haneul-indexer.exe ] && mv ./target/release/haneul-indexer.exe ./target/release/haneul-indexer-${os_type}.exe
+          [ -f ./target/release/haneul-data-ingestion.exe ] &&  mv ./target/release/haneul-data-ingestion.exe ./target/release/haneul-data-ingestion-${os_type}.exe
+          [ -f ./external-crates/move/target/release/move-analyzer.exe ] && mv ./external-crates/move/target/release/move-analyzer.exe ./external-crates/move/target/release/move-analyzer-${os_type}.exe
           tar -cvzf ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz ./target/release/haneul*-${os_type}* ./external-crates/move/target/release/move-analyzer-${os_type}.exe
           [[ ${{ env.haneul_tag }} == *"mainnet"* ]] && aws s3 cp ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz s3://haneul-releases/releases/haneul-${{ env.haneul_tag }}-${os_type}.tgz || true
 
       - name: Upload release artifacts for ${{ matrix.os }} platform
-        if: ${{ env.haneul_tag != 'main' }}
         uses: actions/upload-artifact@v3
         with:
           name: haneul-binaries-${{ matrix.os }}
@@ -141,7 +165,6 @@ jobs:
             ./target/release/haneul-${{ env.haneul_tag }}-${{ env.os_type }}.tgz
 
       - name: Publish binaries for ${{ env.haneul_tag }} release
-        if: ${{ env.haneul_tag != 'main' }}
         uses: softprops/action-gh-release@v1
         with:
           tag_name: ${{ env.haneul_tag }}
@@ -149,10 +172,16 @@ jobs:
             ./target/release/haneul-${{ env.haneul_tag }}-${{ env.os_type }}.tgz
 
   update-homebrew-formula:
+    name: Push binaries to homebrew
     needs: release-build
     runs-on: ubuntu-latest
-    if: ${{ contains(github.ref, 'mainnet') }}
+    if: ${{ contains( inputs.haneul_tag, 'mainnet') || contains( github.ref, 'mainnet') }}
     steps:
+      - name: Clean up tag name ${{ env.TAG_NAME }}
+        shell: bash
+        run: | 
+          echo "haneul_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
+
       # Checkout HaneulLabs/homebrew-tap
       - name: Checkout Target Repository
         uses: actions/checkout@v3
@@ -163,11 +192,6 @@ jobs:
           ref: main
           fetch-depth: 0
 
-      - name: Clean up tag name ${{ env.TAG_NAME }}
-        shell: bash
-        run: | 
-          echo "haneul_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
-
       # Download all artifacts from the previous job
       - name: Download all artifacts
         uses: actions/download-artifact@v2
@@ -175,11 +199,11 @@ jobs:
       - name: Fetch Ubuntu x86_64 Binary and Compute SHA256
         shell: bash
         run: |
-          echo "sha256_ubuntu_release=$(sha256sum haneul-binaries-ubuntu-ghcloud/haneul-${haneul_tag}-ubuntu-x86_64.tgz | awk '{print $1}')" >> $GITHUB_ENV
-          echo "sha256_macos_x86_release=$(sha256sum haneul-binaries-macos-latest-xl/haneul-${haneul_tag}-macos-x86_64.tgz  | awk '{print $1}')" >> $GITHUB_ENV
-          echo "sha256_macos_arm_release$(sha256sum haneul-binaries-macos-arm64-self-hosted/haneul-${haneul_tag}-macos-arm64.tgz | awk '{print $1}' )" >> $GITHUB_ENV
+          echo "sha256_ubuntu_release=$(sha256sum haneul-binaries-ubuntu-ghcloud/haneul-${{ env.haneul_tag }}-ubuntu-x86_64.tgz | awk '{print $1}')" >> $GITHUB_ENV
+          echo "sha256_macos_x86_release=$(sha256sum haneul-binaries-macos-latest-xl/haneul-${{ env.haneul_tag }}-macos-x86_64.tgz  | awk '{print $1}')" >> $GITHUB_ENV
+          echo "sha256_macos_arm_release=$(sha256sum haneul-binaries-macos-arm64-self-hosted/haneul-${{ env.haneul_tag }}-macos-arm64.tgz | awk '{print $1}' )" >> $GITHUB_ENV
           
-    # Install Jinja2 for templating
+      # Install Jinja2 for templating
       - name: Install Jinja2
         run: pip install jinja2
 
